[package]
name = "forge-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
oas = "0.1.1"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7.1"
thiserror = "1.0"
shlex = "1.3.0"

# Tokio is configured for WASM by disabling default features (like 'net') 
# and only enabling the ones we need.
tokio = { version = "1.0", default-features = false, features = ["rt", "macros"] }
