[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
authors = ["{{authors}}"]
default-run = "{{project-name}}-server"

[lib]
name = "{{project-name | snake_case}}"
path = "src/lib.rs"

[[bin]]
name = "{{project-name}}-server"
path = "src/main.rs"

[[bin]]
name = "openapi-spec-generator"
path = "src/bin/openapi-spec-generator.rs"

[[bin]]
name = "api-cli"
path = "src/bin/api-cli.rs"
required-features = ["service_kit/api-cli"]

[dependencies]
service_kit = { version = "0.1.0", features = ["api-cli"] }
anyhow = "1.0" # Added for the api-cli binary

# Web framework
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# OpenAPI & Schema
utoipa = { version = "5.4", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0", features = ["axum"] }

# TypeScript generation
ts-rs = "11.0"

# Environment variables
dotenvy = "0.15"
