[package]
name = "service-kit-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
heck = "0.5.0"
ctor = "0.2.7"
